name: "🐛 Bug Report"
description: Report a bug in Client/Creator
labels: [
  "bug"
]
body:
  - type: markdown
    attributes:
      value: |
        Notice !! Before creating an issue, please make sure to follow the guidelines:
        - **Always open an issue for one bug only**, if you have multiple bugs you wanted to report. Please split them into multiple issues.
        - **Search for existing issue** to ensure it has not already been reported. If you're unsure or there isn't any, feel free to **create a new one**! The maintainers will look into it.
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please describe the description of the bug
      placeholder: Short description of the bug...
    validations:
      required: true
  - type: input
    id: system_info
    attributes:
      label: "System Information"
      description: Your system details. If using Creator, you can copy the details from Help > Copy System Info
      placeholder: Swag PC Core i9
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please list steps on how to replicate your issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: ""
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output (Typically located in AppData/PolytoriaClient/logs/godot.log)
      render: bash
    validations:
      required: false